services:
  #frontend:
    #build:
    #  context: ./services/frontend
    #container_name: frontend-service
    #ports:
    #  - "8081:8080"
    #environment:
    #  - XYZ=abc
    #restart: unless-stopped


  backend:
    build:
      context: ./services
      dockerfile: backend/Dockerfile
    container_name: backend-service
    ports:
      - "8000:8000"
    volumes:
      - ./services/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000" ]

