services:
  frontend:
    build:
      context: ./services/frontend/
    container_name: frontend-service
    ports:
      - "8080:8082"
    environment:
      - XYZ=abc
    restart: unless-stopped


  backend:
    build:
      context: .services/backend
    container_name: backend-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    command: [ "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000" ]
