services:
  frontend:
    build:
      context: ./service/frontend
    container_name: frontend-service
    ports:
      - "8081:8080"
    environment:
      - XYZ=abc
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: services/backend/Dockerfile
    container_name: backend-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000" ]

