name: "PR Label"

on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
